### ISSUE TITLE
Icons vertical alignment

### ISSUE THREAD

**Issue by MihajloLazar1** [db-ui/mono#2270]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [X] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

It looks like icons are not properly vertically aligned.

1. Import necessary styles, in our case: 
```scss 
// Library import from DB UI Mono V3
// Combined dependencies like variables, colors and tonality and all components
@forward '@db-ui/components/build/styles/db-ui-42-rollup';
// We use $db-spacing-fixed-md variable so we need to import the file where the variable is defined
@use '@db-ui/foundations/build/scss/variables';
// Color-classes are optional, we use them in the example to have easy access to colors
@forward '@db-ui/foundations/build/css/colors/classes/all';
```
2. Use one icon (e.g. `add_circle`):
```tsx
const root = createRoot(document.getElementById('root')!);
root.render(<span data-icon="add_circle"></span>);
```
![image](https://github.com/db-ui/mono/assets/161047514/16c5d29c-6684-4982-9936-ee8aa4a7cb83)

3. Another example with the `DBButton` component (magnified in browser to 500%):
```tsx
const root = createRoot(document.getElementById('root')!);
root.render(
	<DBButton type="button" variant="outlined" size="small">
		<span data-icon="edit"></span>
	</DBButton>
);
```
![image](https://github.com/db-ui/mono/assets/161047514/b1baa293-fd21-4a5a-862d-bef6b41226bd)

### Expected Behaviour

All icons are properly vertically and horizontally centered.

### Browser version

None

**Comment by nmerget** [comment]
Thanks for the report, I created https://github.com/db-ui/mono/pull/2271.

The `<DBIcon>` had already a fix for the problem. But indeed it wasn't on the `<span data-icon="XXX">`.

The issue with the button can be solved by using the `icon` prop on the button directly:

`<DBButton icon="edit">...</DBButton>`

We provide `icon` to some components to add it to the correct position, because `data-icon` will add a pseudo element `::before` which may not be correct positioned like in the example with the button.
