### ISSUE TITLE
Accordion use input(type=radio/checkbox) instead of details/summary

### ISSUE THREAD

**Issue by nmerget** [db-ui/mono#2402]
We should consider switching to details/summary for accordion to get rid of the JS implementation for Accordion.

Initially saw it here: https://daisyui.com/components/accordion/ (working with CSS only)

^----- Current idea from my side:

````
<ul class="db-accordion">
<li class="db-accordion-item">
<label><input type="checkbox" name="acc"/>Title</label>
... Slot ...
</li>
<li class="db-accordion-item">
<label><input type="checkbox" name="acc"/>Title</label>
... Slot ...
</li>
</ul>
````

In case of using this, we would need to further enhance it via `aria-`-attributes. Or keep the existing `details/summary`, if we know the timeline regarding Firefox's [`name`-attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details#name) support.

**Comment by mfranzke** [comment]
@nmerget could you please provide a link to an article, gist or whatever, if a ressource like this already exists?

**Comment by bruno-sch** [comment]
Behaviour `multiple` can be implemented with checkboxes. Behaviour `single` requires radio buttons.

A pure CSS solution unfortunately seems limited to me: Since radio buttons cannot be _unchecked_ without JS, there is no way to close the opened item by clicking on it (behaviour `single`).

Both variants can be seen here: https://codepen.io/alvarotrigo/pen/dyJbqpd

**Comment by mfranzke** [comment]
As the native support will be provided by beginning of September, we shouldn't proceed with this.
