### ISSUE TITLE
DBNavigation/DBNavigationItem not as expected

### ISSUE THREAD

**Issue by StefanSeligerBahn** [db-ui/mono#2993]
### Which generators are impacted?

- [ ] All
- [ ] HTML
- [X] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

I implemented the DBNavigation & DBNavigationItem. If a DBNavigationItem has a subNavigation attribute the items behave as expected, but without the DBNavigationItem are not as expected. See file attached. I didn't use an <a> tag for the DBNavigationItem "Einstellungen" e.g.

![DBNavigationItems](https://github.com/user-attachments/assets/13f6bb88-4c7b-4be4-b50a-87075a3c2d99)

### Expected Behaviour

I expected the DBNavigationItem to look all the same. Even if I don't use an <a> tag. An I am not sure that an <a> tag is always necessary. Why not a button? 

### Browser version

None

### Add any other context about the problem here.

![DBNavigation](https://github.com/user-attachments/assets/6bc45388-952f-4245-b638-9df3eb8a8a13)

Also this link to how to use it in react doesn't work. And the example code snippet doesn't represent the example shown completely.

**Comment by nmerget** [comment]
I changed the docs [here](https://github.com/db-ui/mono/pull/3031). You are right an inner tag for the `DBNavigationItem` was missing.

> I expected the DBNavigationItem to look all the same. Even if I don't use an tag. An I am not sure that an tag is always necessary. Why not a button?

To answer your question why there should be another tag inside the `DBNavigationItem`:

There are different routers for different frameworks. Right now the `DBNavigationItem` represents just an `<li>` without anything or if you provide a `subNavigation` it contains a `button` + `menu`. We don't force something like an `<a>` inside the `DBNavigationItem`, because if a developer would like to use e.g. [react-router](https://reactrouter.com/en/main) the developer needs the custom `<Link>` component. Therefore, we need to keep the children/slot open to pass in any custom component or the default anchor tag.

Why don't we use a `button` for routing?
We recommend that you don't use a button for routing. This leads to an accessibility and UX problem because you get some invisible routing:

1. Screen Reader user can jump to `<a>` tags and will know that the interaction will change the route
2. As a default user you can right-click on a link and copy it.
3. As a default user you can hover over a link and see the preview (chrome) in the left corner
